### ISSUE TITLE
Conceptual difference between Operation and Future

### ISSUE THREAD

**Issue by emartynov** [RedMadRobot/Chronos#1]
I was pointed to library through internal chat.

Some things already catch my attention and one of them - `Operation` class in comparing to `Future`.

Did you consider to use it?

**Comment by MaximEfimovRMR** [comment]
Thank you for your interest!

In fact, Futures are used deep inside the library. But there is a big difference between Future and Operation – the last one is a class similar to Callable interface. Callable can be aggregate by Future, so in that way Future relates to Operation class as "contains". 
While Future describes an entity which is "running", Operation only declares some entity which "can be run". That difference distance Operation content from the way it will be executed, and thus user has to know nothing about blocking executions, thread joining and other multithread concepts, concentrating only on writing business logic.

**Comment by emartynov** [comment]
Thank you a lot for clarifications!

So `Operation` class is closer to `Callable` but still have notion about was it executed or cancelled.
One more addition that `Future` class doesn't expose also anything about multithreading. 

I will close the issue. Bad that there is no ticket types like a question :)
Thank you for conversation.
