### ISSUE TITLE
Publishing Progress

### ISSUE THREAD

**Issue by m-Samhoury** [RedMadRobot/Chronos#3]
Is there a possible neat way to publish progress of how much the background job has reached?

**Comment by MaximEfimovRMR** [comment]
There is no such Chronos option yet. You can use EventBus to do it.

**Comment by IlyaEremin** [comment]
I don't believe in progress :\

**Comment by arkty** [comment]
@m-Samhoury you can push progress value into a database and then handle it in activity. For example, for file download you can create a record:
`class DownloadProgress {
int downloadId;
long totalBytes;
long downloadedBytes;
}
`
And then you can use Observers, Rx, or build in notifications(e.x. Realm change listeners) to handle progress in UI.
With this simple approach you can handle simple(downloading data) or complex(serial network requests) situations.
