### ISSUE TITLE
Determine operation status

### ISSUE THREAD

**Issue by IliaEremin** [RedMadRobot/Chronos#5]
Кейс:
1. Запускается долгая операция.
2. Переворот экрана
3. Операция все еще выполняется.
Есть ли способ средствами хроноса понять это? Или надо пилить это дело самому?

**Comment by MaximEfimovRMR** [comment]
Есть метод isOperationRunning(), в который можно передать либо id запуска (возвращается после запуска операции через runOperation()), либо tag, если операцию запускали с ним. Подробнее про обращение к запущенной операции [здесь](https://github.com/RedMadRobot/Chronos/wiki/Canceling-operations#how-to-reference-a-running-operation).
Так же можно попробовать использовать [Single launch](https://github.com/RedMadRobot/Chronos/wiki/Single-launch-mode), если операция по бизнес-логике стартует вместе с показом экрана.

**Comment by IliaEremin** [comment]
:+1:
