### ISSUE TITLE
org.jetbrains.annotations.NotNull

### ISSUE THREAD

**Issue by RaggaJungler** [RedMadRobot/Chronos#7]
Hi! 
I tried to use Chronos with kotlin but got the error:
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lorg/jetbrains/annotations/NotNull;

My dependencies:

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile ('com.redmadrobot:chronos:1.0.7') {
        exclude  group: 'org.jetbrains', module: 'annotations'
    }
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

}
There are no libraries in 'libs' folder. As you can see I used exclude on chronos but it didn't help.
Could you give me the cue how to fix it?

**Comment by xanderblinov** [comment]
Hi!

try to use `com.redmadrobot:chronos-kotlin:1.0.7` 

[chronos-kotlin:1.0.7](https://bintray.com/rmr/maven/chronos-kotlin) from [master_kotlin](https://github.com/RedMadRobot/Chronos/tree/master_kotlin) branch

It's special version with kotlin support. Special thanks for @ejohnic for quick fix
